name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v3
      - run: go version
